export * from './resetThreeStep'
export * from './setLampColor'
export * from './setControlType'
export * from './setGlowTemperature'
export * from './setLampPower'
export * from './setLampsSide'
export * from './setCatalogCategory'